name: Pylint and unittest

on: [push, pull_request]

jobs:
  build:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
        - uses: actions/checkout@v4
        - name: Install uv
          uses: astral-sh/setup-uv@v5
          with:
            enable-cache: true
            python-version: ${{ matrix.python-version }}

        - name: Install dependencies
          run: uv sync --all-extras

        - name: Analyzing the code with pylint
          run: uv run pylint $(git ls-files '*.py') || true

        - name: Run unit tests
          run: uv run python -m unittest discover -v -s tests -t . -p "test_*.py"
